import Link from "next/link";
import { SiteHeader } from "./components/SiteHeader";
import { EvidenceMark } from "./components/EvidenceMark";
import { event, sources } from "./data";

export const metadata = {
  title: "StudentVoice — Evidence, not outrage",
  description:
    "A bilingual civic evidence platform for verified timelines, protected sources, and accountable public-interest reporting.",
};

export default function Home() {
  const corroborated = event.claims.filter((claim) => claim.status === "corroborated").length;

  return (
    <>
      <SiteHeader />
      <main>
        <section className="hero shell" aria-labelledby="hero-title">
          <div className="hero-copy">
            <p className="eyebrow"><span className="live-dot" /> Public-interest evidence archive</p>
            <h1 id="hero-title">Evidence,<br /><em>not outrage.</em></h1>
            <p className="hero-intro">
              StudentVoice preserves what happened, separates verified facts from allegations,
              and protects the people who document public events.
            </p>
            <p className="hero-hindi" lang="hi">सबूत सुरक्षित। दावे स्पष्ट। स्रोत संरक्षित।</p>
            <div className="hero-actions">
              <Link className="button button-primary" href="/events/jantar-mantar-july-20">
                Open the evidence timeline <span aria-hidden="true">↗</span>
              </Link>
              <Link className="button button-quiet" href="/submit">Submit evidence</Link>
            </div>
          </div>

          <aside className="dispatch-card" aria-label="Current investigation">
            <div className="dispatch-topline">
              <span>CASE SV–DEL–0720</span>
              <span className="status-pill status-active">Active review</span>
            </div>
            <p className="dispatch-date">20 JUL 2026 · NEW DELHI</p>
            <h2>Jantar Mantar<br />“Chalo Sansad” protest</h2>
            <p className="dispatch-summary">
              A source-by-source reconstruction of the march, police response,
              reported injuries, detentions, and the communications shutdown.
            </p>
            <div className="dispatch-stats">
              <div><strong>{sources.length}</strong><span>seed sources</span></div>
              <div><strong>{event.timeline.length}</strong><span>time points</span></div>
              <div><strong>{corroborated}</strong><span>corroborated claims</span></div>
            </div>
            <Link className="text-link" href="/events/jantar-mantar-july-20">Review the case file →</Link>
          </aside>
        </section>

        <section className="principles-band" aria-labelledby="principles-title">
          <div className="shell">
            <div className="section-kicker"><span>01</span><p>How trust is built</p></div>
            <div className="principles-heading">
              <h2 id="principles-title">Every public claim carries its own audit trail.</h2>
              <p>We publish the evidence around a claim—including disagreement—not a verdict generated by a model.</p>
            </div>
            <div className="principles-grid">
              <article><span className="principle-number">A</span><h3>Preserve</h3><p>Original bytes, filenames, acquisition records, and hashes are retained before analysis begins.</p></article>
              <article><span className="principle-number">B</span><h3>Corroborate</h3><p>Independent sources, timestamps, and competing accounts are reviewed side by side.</p></article>
              <article><span className="principle-number">C</span><h3>Protect</h3><p>Witnesses, minors, bystanders, medical information, and precise locations are redacted by default.</p></article>
              <article><span className="principle-number">D</span><h3>Correct</h3><p>Published records are versioned. Replies, appeals, corrections, and retractions remain visible.</p></article>
            </div>
          </div>
        </section>

        <section className="case-preview shell" aria-labelledby="known-title">
          <div className="section-kicker"><span>02</span><p>The record so far</p></div>
          <div className="case-preview-grid">
            <div>
              <h2 id="known-title">What the reviewed record supports—and what it does not.</h2>
              <p className="section-lead">Status labels describe the state of the evidence. They are not popularity scores.</p>
            </div>
            <div className="claim-list">
              {event.claims.slice(0, 4).map((claim) => (
                <article className="claim-row" key={claim.id}>
                  <EvidenceMark status={claim.status} />
                  <div><h3>{claim.title}</h3><p>{claim.summary}</p></div>
                  <span className={`status-label status-${claim.status}`}>{claim.status.replace("_", " ")}</span>
                </article>
              ))}
              <Link className="button button-outline" href="/events/jantar-mantar-july-20#claims">See all claims and citations</Link>
            </div>
          </div>
        </section>

        <section className="source-strip" aria-labelledby="sources-title">
          <div className="shell source-strip-inner">
            <div><p className="eyebrow">Balanced source register</p><h2 id="sources-title">Reporting, official accounts, rights groups, and primary footage.</h2></div>
            <div className="source-names" aria-label="Seed source organizations">
              {sources.map((source) => <span key={source.id}>{source.publisher}</span>)}
            </div>
          </div>
        </section>

        <section className="closing-cta shell">
          <p className="eyebrow">Document responsibly</p>
          <h2>Were you there?</h2>
          <p>Share an original file or a public link. You may submit once without creating an account.</p>
          <Link className="button button-primary" href="/submit">Start a protected submission</Link>
        </section>
      </main>
      <footer className="site-footer">
        <div className="shell footer-grid">
          <div><strong>STUDENTVOICE</strong><p>Open-source civic evidence infrastructure.</p></div>
          <nav aria-label="Footer"><Link href="/methodology">Methodology</Link><Link href="/submit">Submit</Link><a href="https://github.com/Starkprince-Inc/studentvoice" target="_blank" rel="noreferrer">GitHub repository ↗</a></nav>
          <p className="footer-note">No biometric identification. No public crowd-sourced naming. मशीन सुझाव प्रकाशित तथ्य नहीं हैं।</p>
        </div>
      </footer>
    </>
  );
}
